[package]
name = "yaffe-rs"
version = "0.7.1"
authors = ["allex"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite3 = "0.24.0"
speedy2d = { version = "1.7.0", default-features = false, features = ["image-loading"] }
spmc = "^0.3"
chrono = "^0.4"
serde_json = "^1"
serde = { version = "^1", features = ["derive"] }
reqwest = { version = "^0.11", features = ["blocking"] }
backtrace = "0.3.64"
image = "0.24.*"
glutin = "^0.28"
takeable-option = "0.5"
memoffset = "0.6.5"
dlopen = "0.1.8"
dlopen_derive = "0.1.3"
lazy_static = "1.4.0"
yaffe-plugin = { path = "../yaffe-plugin" }
simple_logger = { version = "1.11", default-features = false, features = ["colors"] }

[target.'cfg(target_os="windows")'.dependencies.winapi]
version = "0.3.9"
features = ["libloaderapi", "winerror", "std", "taskschd", "impl-default", "oleauto", "objbase", "xinput", "mmdeviceapi", "endpointvolume"]

[target.'cfg(target_os="linux")'.dependencies]
libc = "0.2.120"
x11 = "2.19.1"
#alsa = "0.6.0"