[package]
name = "yaffe-plugin"
version = "0.1.0"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
#uuid = { version = "0.8", features = ["v4"] }
